# frozen_string_literal: true

source 'https://rubygems.org'

gem 'sinatra'
gem 'facebook-messenger'
gem 'rack'
gem 'rack-test'
gem 'rake'
gem 'dotenv'
gem 'rerun'
gem 'pry'
gem 'firebase'
gem 'rspec'
gem 'rest-client'
gem 'capistrano'
gem 'capistrano-bundler'
gem 'capistrano-passenger'
gem 'capistrano-rvm'
gem 'webmock'
gem 'loga'
